### ISSUE TITLE
Testing NGRX

### ISSUE THREAD

**Issue by RicardoVaranda** [toddmotto/ac-boilerplate#1]
Hi Todd,

Do you have any guides/tutorials on testing ngrx effects, reducers and selectors, I've been looking around and haven't found any proper up to date (ngrx 4) material

Thanks!

**Comment by toddmotto** [comment]
Hey Ricardo! Yes, it'll be about 10 days or so, but I'm releasing a free course that provides all of this here: https://ultimateangular.com/ngrx-store-effects

I hope it answers all the above questions you have 💃
